import React from 'react'

function Story() {
    
    return (
        <div className="story">
            Story
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis faucibus sem, fermentum accumsan odio luctus vel. Donec non ex facilisis, dictum velit nec, varius risus. Pellentesque metus lectus, imperdiet nec odio quis, varius finibus ligula. Nullam venenatis, neque a eleifend accumsan, nunc sapien congue ligula, ut faucibus ligula purus eu risus. Nullam felis justo, ultricies a arcu et, ultricies fermentum dolor. Etiam eleifend cursus diam, malesuada congue lectus congue ac. Phasellus malesuada, lorem id maximus commodo, nibh risus convallis dui, eu bibendum urna sapien sed sem. Quisque a vestibulum ante. Fusce ornare congue nunc non hendrerit. Aenean id nunc sit amet ipsum ornare congue. Vestibulum eu nunc erat. Praesent et est nibh. Proin porttitor feugiat sapien, non semper purus gravida ac. Nulla convallis sodales quam at varius. Sed vitae diam suscipit, volutpat odio eget, tempus erat.

Morbi varius felis eget finibus gravida. Morbi feugiat maximus diam sed faucibus. Morbi blandit mauris in sollicitudin pretium. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque facilisis, nunc vel consequat facilisis, magna elit pharetra augue, at sollicitudin nunc nisl et mauris. Phasellus et blandit lorem, eu venenatis arcu. Phasellus augue felis, hendrerit in velit in, consectetur accumsan ligula. Vestibulum auctor dui vel nisi facilisis consequat. Integer odio sapien, iaculis ut consequat dictum, suscipit vel lacus. Maecenas consectetur enim lobortis diam venenatis luctus. Duis dignissim dapibus ipsum. Aenean at nisi imperdiet, venenatis mi et, blandit lectus. Sed ultrices et lectus vitae tincidunt. Nulla nisi est, rhoncus sed malesuada sit amet, commodo vitae purus. Praesent maximus sit amet felis eget porta.

Nam dui metus, dictum sed eros et, gravida ultricies risus. Pellentesque sed nisi nulla. Vestibulum suscipit bibendum mi, eu scelerisque leo laoreet eu. Fusce vel commodo lectus. Ut lacinia nibh iaculis, ultrices dui vitae, laoreet mauris. Praesent tempor feugiat sapien luctus ultrices. Praesent turpis enim, posuere quis luctus id, cursus et risus. Pellentesque imperdiet est sit amet purus iaculis, non pellentesque neque suscipit. Pellentesque viverra, erat eleifend commodo consequat, ante massa lobortis quam, et dictum augue nulla eu ipsum. Maecenas faucibus sit amet augue quis varius. Nullam feugiat justo non convallis condimentum. Curabitur nisl urna, bibendum eget lacinia sit amet, lobortis quis tortor. Proin vitae ipsum ligula. Maecenas volutpat, enim at pharetra porta, odio erat fermentum felis, ut rutrum sapien sapien eget augue. Duis egestas ac lacus in fringilla. Curabitur feugiat arcu urna, imperdiet tincidunt enim tincidunt quis.

In nec est neque. In auctor, augue rutrum luctus luctus, arcu velit pretium nisl, quis interdum nisl est vitae tellus. In hac habitasse platea dictumst. Donec eleifend elementum lacinia. Sed euismod ultricies dignissim. Integer scelerisque pharetra mauris. Quisque et felis quis leo pharetra eleifend. Suspendisse rutrum, mi non dictum volutpat, nibh felis placerat eros, vel mollis tellus ipsum vitae elit. Cras luctus aliquam velit a malesuada. Ut magna est, molestie a aliquet in, tempus ut mi. Integer vel gravida lorem, ac scelerisque tortor. Quisque quis lobortis eros. Vestibulum sit amet mattis odio. Fusce tincidunt sem id tortor fermentum, ac efficitur lectus gravida. Duis ligula felis, tempus commodo vulputate sit amet, efficitur et leo.

Mauris id sagittis metus. Vestibulum molestie elit sit amet fermentum ultrices. Suspendisse dapibus erat non tempor dapibus. Nam efficitur sapien sit amet aliquam tristique. Maecenas elementum massa at risus tempor lacinia. Duis sit amet sapien lobortis, pellentesque tellus quis, cursus diam. Proin at nisl risus. Aenean placerat tempor ultrices. Donec egestas egestas sapien, a pretium orci hendrerit et. Nullam tellus urna, consectetur aliquam lectus a, ultrices vehicula velit. Mauris id mi venenatis, pretium turpis nec, faucibus augue.</p>
        </div>
    )
}

export default Story
